package bulletinfo.com.bulletinfo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bulletinfo.com.bulletinfo.bean.Friends;
import bulletinfo.com.bulletinfo.bean.User_Message;

import bulletinfo.com.bulletinfo.greendao.FriendsDao;
import bulletinfo.com.bulletinfo.greendao.User_MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsDaoConfig;
    private final DaoConfig user_MessageDaoConfig;

    private final FriendsDao friendsDao;
    private final User_MessageDao user_MessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
        friendsDaoConfig.initIdentityScope(type);

        user_MessageDaoConfig = daoConfigMap.get(User_MessageDao.class).clone();
        user_MessageDaoConfig.initIdentityScope(type);

        friendsDao = new FriendsDao(friendsDaoConfig, this);
        user_MessageDao = new User_MessageDao(user_MessageDaoConfig, this);

        registerDao(Friends.class, friendsDao);
        registerDao(User_Message.class, user_MessageDao);
    }
    
    public void clear() {
        friendsDaoConfig.clearIdentityScope();
        user_MessageDaoConfig.clearIdentityScope();
    }

    public FriendsDao getFriendsDao() {
        return friendsDao;
    }

    public User_MessageDao getUser_MessageDao() {
        return user_MessageDao;
    }

}
