package bulletinfo.com.bulletinfo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bulletinfo.com.bulletinfo.bean.Friends;

import bulletinfo.com.bulletinfo.greendao.FriendsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsDaoConfig;

    private final FriendsDao friendsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
        friendsDaoConfig.initIdentityScope(type);

        friendsDao = new FriendsDao(friendsDaoConfig, this);

        registerDao(Friends.class, friendsDao);
    }
    
    public void clear() {
        friendsDaoConfig.clearIdentityScope();
    }

    public FriendsDao getFriendsDao() {
        return friendsDao;
    }

}
